---
title: "Untitled"
author: "Jessica Hirsch"
date: '2022-05-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(ggplot2)

source(here::here("functions.R"))
```

```{r}
goodreads <- 
  read_csv(here::here("Data", "books_updated.csv")) %>% 
  mutate(type = "general")

user_jmh <- 
  read_csv(here::here("Data", "JMHbooks.csv")) %>% 
  mutate(type = "JMH")

awards <- 
  read_csv(here::here("Data", "GoodReadsAwards.csv"))

```

```{r}
glimpse(goodreads)

```

```{r}
goodreads <- 
goodreads %>% 
  select(- best_book_id, -original_title, - starts_with("work"), -small_image_url, -toread_count, -currently_reading)

goodreads <- 
goodreads %>% 
rename("publications" = books_count,
       "publication_year" = original_publication_year)

goodreads <- 
goodreads %>% 
  mutate(language_code = case_when(
    str_detect(language_code, pattern = "^[en]") ~ "en",
    TRUE ~ language_code)) 

```


```{r}
summary(awards)

awards %>% 
  filter(is.na(pages)) %>% 
  select(category, rank, year, title) %>% 
  arrange(desc(rank))

awards <- 
awards %>% 
  select(gid, rank, votes, category, year, pages, published) %>% 
  rename("award_rank" = rank,
         "award_votes" = votes,
         "award_category" = category,
         "award_year" = year,
         "date_published" = published)

```

```{r}

goodreads_awards <- 
goodreads %>% 
  left_join(awards, by = c("book_id" = "gid"))

goodreads_awards %>% 
  summarise(across(everything (), ~sum(is.na(.))))

```

```{r}
user_jmh <- 
clean_names(user_jmh)

glimpse(user_jmh)

user_jmh %>% head() %>% dput()

user_jmh <- 
  user_jmh %>% 
  mutate(across(starts_with("date"), ~ lubridate::mdy(.), .names = "{col}")) %>% 
  select(-author_l_f, -year_published, -bookshelves_with_positions) %>%
  rename("format" = binding)  


```

```{r}

jmh_look <- 
user_jmh %>% 
  map_dfr(look, .id = "field")

ga_look <- 
goodreads_awards %>% 
  map_dfr(look, .id = "field")

```

```{r}

ga_nums <- 
ga_look %>% 
  filter(class %in% c("numeric", "date")) %>% 
  pull(field)

map(ga_nums, ~ create_hist(goodreads_awards, .x))

```

```{r}
ga_nums_selected <- 
ga_look %>% 
  filter(class %in% c("numeric", "date"),
        !field %in% c("id", "book_id", "isbn13"),
        !str_detect(field, "._\\d")) %>% 
  pull(field)

ga_nums_combos <-
expand_grid(field_1 = ga_nums_selected,
            field_2 = ga_nums_selected) %>% 
  filter(field_1 != field_2)

map2(ga_nums_combos$field_1,
     ga_nums_combos$field_2,
     ~ create_scatter(goodreads_awards, .x, .y))
  
```

```{r}
glimpse(user_jmh)

jmh_nums <- 
jmh_look %>% 
  filter( class %in% c("numeric", "Date"),
          !field %in% c("book_id", "isbn13")) %>% 
  pull(field)

jmh_char <- 
jmh_look %>% 
  filter(class %in% "character",
         !field %in% c("isbn", "additional_authors", "bookshelves", "type")) %>% 
  pull(field)

```

```{r}
map(jmh_nums, ~ create_hist(user_jmh, .x))
```

```{r}
map(jmh_char, ~ bar_counts(user_jmh, .x))
```

```{r}
glimpse(user_jmh)

user_jmh <- 
user_jmh %>% 
  mutate(format = case_when(
    str_detect(format, "Audio") ~ "Audiobook",
    str_detect(format, "Paper") ~ "Paperback",
    str_detect(format, "Kindle") ~ "ebook",
    str_detect(format, "Nook") ~ "ebook",
    TRUE ~ format)) 

jmh_read <- 
user_jmh %>% 
  filter(exclusive_shelf %in% "read")

jmh_nums_combos <-
expand_grid(field_1 = jmh_nums,
            field_2 = jmh_nums) %>% 
  filter(field_1 != field_2)

map2(jmh_nums_combos$field_1,
     jmh_nums_combos$field_2,
     ~ create_scatter(user_jmh, .x, .y))

```

```{r}
jmh_read <- 
jmh_read %>% 
  mutate(across(starts_with("date"), ~ year(.), .names = "year_{col}"),
         read_time = as.double(date_read - date_started),
         time_to_read = as.double(date_started - date_added))

jmh_read %>% 
  map_dfr(look, .id = "field")
  
jmh_read %>% 
  count(year_date_read) %>% 
  ggplot(aes(x = year_date_read,
             y = n)) +
  geom_line()

```

```{r}
jmh_read %>% 
  group_by(year_date_read) %>% 
  mutate(avg_pages = mean(number_of_pages, na.rm = T)) %>%
  ungroup() %>% 
  ggplot(aes(x = year_date_read,
             y = number_of_pages)) +
  geom_col()
```

```{r}
jmh_read %>%
  ggplot(aes(x = year_date_read,
             y = read_time,
             group = year_date_read)) +
  geom_boxplot() +
  coord_cartesian(ylim = c(0, 100),
                  xlim = c(2010, 2022)) +
  scale_x_continuous(breaks = c(2010, 2014, 2018, 2022)) 


  
```

```{r}

jmh_read %>% 
  group_by(year_date_read) %>% 
  mutate(avg_pages = mean(number_of_pages, na.rm = T),
         avg_time = mean(read_time, na.rm = T)) %>%
  ungroup() %>%
  ggplot(aes(x = year_date_read)) +
  geom_col(aes(y = avg_pages/100)) +
  geom_line(aes(y = avg_time, Color = "blue")) +
  scale_y_continuous(name = "Average Time to Read", sec.axis = sec_axis(trans = ~.*100, name = "Average Pages")) +
  coord_cartesian(xlim = c(2010,2022)) +
  theme_light()



```

```{r}

goodread_tags <- 
goodreads_awards %>% 
  mutate(tag_name = str_split(tag_name, "[\\W]")) %>% 
  unnest(tag_name) %>%
  mutate(across(where(is.character), ~ na_if(., ""))) %>% 
  filter(!is.na(tag_name))


gr_tag_count <- 
goodread_tags%>% 
  mutate(tag_name = case_when(
    str_detect(tag_name, pattern = "witces") ~ "supernatural",
    str_detect(tag_name, pattern = "wish") ~ "To Read",
    str_detect(tag_name, pattern = "young") ~ "YA",
    str_detect(tag_name, pattern = "ya") ~"YA",
    str_detect(tag_name, pattern = "ii") ~ "war",
    str_detect(tag_name, pattern = "vamp") ~ "supernatural",
    str_detect(tag_name, pattern = "urb") ~ "fantasy",
    str_detect(tag_name, pattern = "^[to]") ~ "To Read",
    str_detect(tag_name, pattern = "thril") ~ "thriller",
    str_detect(tag_name, pattern = "^[time]") ~ "SciFi",
    str_detect(tag_name, pattern = "teen") ~ "YA",
    str_detect(tag_name, pattern = "sus") ~ "thriller",
    str_detect(tag_name, pattern = "stars") ~ "astronomy",
    str_detect(tag_name, pattern = "spirit") ~ "spritual",
    str_detect(tag_name, pattern = "space") ~ "SciFi",
    str_detect(tag_name, pattern = "shape") ~ "supernatural",
    str_detect(tag_name, pattern = "sf") ~ "SciFi",
    str_detect(tag_name, pattern = "self") ~ "selfhelp",
    str_detect(tag_name, pattern = "scifi") ~ "SciFi",
    str_detect(tag_name, pattern = "sciencef") ~ "SciFi",
    str_detect(tag_name, pattern = "rom") ~ "romance",
    str_detect(tag_name, pattern = "rel") ~ "religion",
    str_detect(tag_name, pattern = "read") ~ "read",
    str_detect(tag_name, pattern = "post") ~ "dystopian",
    str_detect(tag_name, pattern = "pict") ~ "children",
    str_detect(tag_name, pattern = "para") ~ "supernatural",
    str_detect(tag_name, pattern = "pnr") ~ "supernatural",
    str_detect(tag_name, pattern = "person") ~ "selfhelp",
    str_detect(tag_name, pattern = "own") ~ "owned",
    str_detect(tag_name, pattern = "novel") ~ "novel",
    str_detect(tag_name, pattern = "mys") ~ "mystery",
    str_detect(tag_name, pattern = "new") ~ "adult",
    str_detect(tag_name, pattern = "my[l|b]") ~ "owned",
    str_detect(tag_name, pattern = "mem") ~ "memoir",
    str_detect(tag_name, pattern = "mang") ~ "manga",
    str_detect(tag_name, pattern = "magic") ~ "supernatural",
    str_detect(tag_name, pattern = "lit") ~ "literature",
    str_detect(tag_name, pattern = "kids") ~ "kids",
    str_detect(tag_name, pattern = "juv") ~ "kids",
    str_detect(tag_name, pattern = "hum") ~ "humor",
    str_detect(tag_name, pattern = "historical[f|r]") ~ "historical fiction",
    str_detect(tag_name, pattern = "historical[\\s]") ~ "history",
    str_detect(tag_name, pattern = "highs") ~ "YA",
    str_detect(tag_name, pattern = "highf") ~ "fantasy",
    str_detect(tag_name, pattern = "graphic") ~ "graphic novel",
    str_detect(tag_name, pattern = "generalf") ~ "fiction",
    str_detect(tag_name, pattern = "funny") ~ "humor",
    str_detect(tag_name, pattern = "^fav") ~ "favorite",
    str_detect(tag_name, pattern = "^fan") ~ "fantasy",
    str_detect(tag_name, pattern = "faith") ~ "spiritual",
    str_detect(tag_name, pattern = "espi") ~ "spy",
    str_detect(tag_name, pattern = "^epic") ~ "fantasy",
    str_detect(tag_name, pattern = "ebook") ~ "ebook",
    str_detect(tag_name, pattern = "dys") ~ "dystopian",
    str_detect(tag_name, pattern = "drag") ~ "supernatural",
    str_detect(tag_name, pattern = "detect") ~ "crime",
    str_detect(tag_name, pattern = "dem") ~ "supernatural",
    str_detect(tag_name, pattern = "crime") ~ "crime",
    str_detect(tag_name, pattern = "contem") ~ "contemproary",
    str_detect(tag_name, pattern = "c[รณ|o]mi") ~ "graphic novel",
    str_detect(tag_name, pattern = "come") ~ "humor",
    str_detect(tag_name, pattern = "classic") ~ "classics",
    str_detect(tag_name, pattern = "christ") ~ "spiritual",
    str_detect(tag_name, pattern = "child") ~ "children",
    str_detect(tag_name, pattern = "chick") ~ "romance",
    str_detect(tag_name, pattern = "booksto") ~ "To Read",
    str_detect(tag_name, pattern = "^bio") ~ "biography",
    str_detect(tag_name, pattern = "^aud") ~ "audiobook",
    str_detect(tag_name, pattern = "^amer") ~ "american",
    str_detect(tag_name, pattern = "^adu") ~ "adult",
    str_detect(tag_name, pattern = "abandoned") ~ "dnf",
    TRUE ~ tag_name
  ))%>% 
  count(tag_name)%>% 
  filter(n > 100) %>% 
  arrange(desc(n)) 
  
```

  
```{r}
gr_tag_count %>%
  filter(n > 500) %>% 
  ggplot(aes(y = tag_name,
             x = n)) +
  geom_col()
```

